name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install --global pnpm

      - name: Install deps
        run: pnpm m i

      - name: Build plugin(s)
        run: pnpm exec lune ci

      - name: Copy additional files
        run: |
          cp -r assets dist
          cp README.md dist/README.md
          printf -- "---\npermalink: /404.html\n---\n" > dist/404.md
          printf -- "> **Note:** You accessed a link that returned a 404, probably by clicking one of the plugin links. You're supposed to copy the link address and add it into shelter.\n\n" >> dist/404.md
          cat README.md >> dist/404.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true
